server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hbd_onf_u
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 150
      max-lifetime: 1800000
      pool-name: HikariCP
  jpa:
    hibernate.ddl-auto: update

logging:
  slack:
    webhook-uri:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
jwt:
  header: Authorization
  token-validity-in-seconds: 86400


